//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string autor { get; set; }
        public string editora { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> estoque { get; set; }
        public Nullable<double> valor { get; set; }
    }
}
